
all:
	@g++ dijsktra.cpp -o dijsktra

execute:
	@g++ dijsktra.cpp -o dijsktra
	@./dijsktra < entrada_dijsktra.txt

# Caso queira apenas compilar o código digite "make".
# Caso queira compilar e executar o código com as entradas pré-definidas, digite "make execute".