
all:
	@g++ prim.cpp -o prim

execute:
	@g++ prim.cpp -o prim
	@./prim < entrada_prim.txt

# Caso queira apenas compilar o código digite "make".
# Caso queira compilar e executar o código com as entradas pré-definidas, digite "make execute".