Por falta de experiência, infelizmente não conseguimos e nem entendemos como implementar o makefile.
Este arquivo servirá para demonstrar como executar este algoritmo.

A execução deve ser feita da seguinte maneira:
- Em um terminal, acesse o diretórios onde os arquivos se localizam;
- Insira o comando: "g++ dijsktra.cpp -o dijsktra" para compilar;
- Em seguida: "./dijsktra < entrada_dijsktra.txt" para executar.