
all:
	@g++ bellman_ford.cpp -o bellman_ford

execute:
	@g++ bellman_ford.cpp -o bellman_ford
	@./bellman_ford < entrada_bellman_ford.txt

# Caso queira apenas compilar o código digite "make".
# Caso queira compilar e executar o código com as entradas pré-definidas, digite "make execute".