
all:
	@g++ kosaraju.cpp -o kosaraju

execute:
	@g++ kosaraju.cpp -o kosaraju
	@./kosaraju < entrada_kosaraju.txt

# Caso queira apenas compilar o código digite "make".
# Caso queira compilar e executar o código com as entradas pré-definidas, digite "make execute".